import { defineStore } from "pinia";

export const useStore = defineStore("main", {
  state: () => ({
    pieceImages: {
      white_pawn: "./assets/img/WhitePawn.png",
      white_rook: "./assets/img/WhiteRook.png",
      white_knight: "./assets/img/WhiteKnight.png",
      white_bishop: "./assets/img/WhiteBishop.png",
      white_king: "./assets/img/WhiteKing.png",
      white_queen: "./assets/img/WhiteQueen.png",
      black_pawn: "./assets/img/BlackPawn.png",
      black_rook: "./assets/img/BlackRook.png",
      black_knight: "./assets/img/BlackKnight.png",
      black_bishop: "./assets/img/BlackBishop.png",
      black_king: "./assets/img/BlackKing.png",
      black_queen: "./assets/img/BlackQueen.png",
    },
    pieces: [
      {
        id: "a8",
        color: "black",
        img: "./assets/img/BlackRook.png",
        name: "Rook",
      },
      {
        id: "b8",
        color: "black",
        img: "./assets/img/BlackKnight.png",
        name: "Knight",
      },
      {
        id: "c8",
        color: "black",
        img: "./assets/img/BlackBishop.png",
        name: "Bishop",
      },
      {
        id: "d8",
        color: "black",
        img: "./assets/img/BlackQueen.png",
        name: "Queen",
      },
      {
        id: "e8",
        color: "black",
        img: "./assets/img/BlackKing.png",
        name: "King",
      },
      {
        id: "f8",
        color: "black",
        img: "./assets/img/BlackBishop.png",
        name: "Bishop",
      },
      {
        id: "g8",
        color: "black",
        img: "./assets/img/BlackKnight.png",
        name: "Knight",
      },
      {
        id: "h8",
        color: "black",
        img: "./assets/img/BlackRook.png",
        name: "Rook",
      },
      {
        id: "a1",
        color: "white",
        img: "./assets/img/WhiteRook.png",
        name: "Rook",
      },
      {
        id: "b1",
        color: "white",
        img: "./assets/img/WhiteKnight.png",
        name: "Knight",
      },
      {
        id: "c1",
        color: "white",
        img: "./assets/img/WhiteBishop.png",
        name: "Bishop",
      },
      {
        id: "d1",
        color: "white",
        img: "./assets/img/WhiteQueen.png",
        name: "Queen",
      },
      {
        id: "e1",
        color: "white",
        img: "./assets/img/WhiteKing.png",
        name: "King",
      },
      {
        id: "f1",
        color: "white",
        img: "./assets/img/WhiteBishop.png",
        name: "Bishop",
      },
      {
        id: "g1",
        color: "white",
        img: "./assets/img/WhiteKnight.png",
        name: "Knight",
      },
      {
        id: "h1",
        color: "white",
        img: "./assets/img/WhiteRook.png",
        name: "Rook",
      },
      {
        id: "a7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "b7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "c7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "d7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "e7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "f7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "g7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "h7",
        color: "black",
        img: "./assets/img/BlackPawn.png",
        name: "Pawn",
      },
      {
        id: "a2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "b2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "c2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "d2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "e2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "f2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "g2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
      {
        id: "h2",
        color: "white",
        img: "./assets/img/WhitePawn.png",
        name: "Pawn",
      },
    ],
  }),
});
